import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any

def save_intermediate_result(phase: str, data: Dict[str, Any], output_dir: Path = None):
    """Lưu kết quả trung gian của từng phase"""
    if output_dir is None:
        output_dir = Path("temp")
    
    output_dir.mkdir(exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = output_dir / f"{phase}_{timestamp}.json"
    
    # Convert pydantic models to dict if needed
    if hasattr(data, 'dict'):
        data = data.dict()
    
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"   💾 Saved: {filename}")
    return filename

def create_final_solution_script(results: Dict[str, Any], output_dir: Path = None) -> str:
    """Tạo script cuối cùng hoàn chỉnh"""
    if output_dir is None:
        output_dir = Path("outputs")
    
    output_dir.mkdir(exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    script_filename = output_dir / f"digit_prime_classifier_{timestamp}.py"
    
    # Get code components
    preprocessing = results.get('preprocessing_code')
    processing = results.get('processing_code')
    postprocessing = results.get('postprocessing_code')
    
    final_script_content = f'''#!/usr/bin/env python3
"""
DIGIT TO PRIME CLASSIFIER
Generated by MultiAgent System at: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Task: Classify handwritten digits as prime or non-prime numbers
Input: Images folder with 28x28 grayscale digit images
Output: CSV file with file_name and prediction columns
"""

{preprocessing.code_imports if preprocessing else "# Imports will be added here"}

import pandas as pd
import numpy as np
from pathlib import Path
import logging

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Prime number checker
def is_prime(digit):
    """Check if digit 0-9 is prime number"""
    prime_digits = {{2, 3, 5, 7}}
    return digit in prime_digits

def digit_to_prime_label(digit):
    """Convert digit to prime/non-prime label"""
    if is_prime(digit):
        return "số nguyên tố"
    else:
        return "không nguyên tố"

{preprocessing.preprocessing_functions if preprocessing else "# Preprocessing functions will be added here"}

{processing.model_loading if processing else "# Model loading code will be added here"}

{processing.inference_pipeline if processing else "# Inference pipeline will be added here"}

{postprocessing.output_formatting if postprocessing else "# Output formatting will be added here"}

def main():
    """Main execution function"""
    logger.info("Starting Digit to Prime Classification Pipeline...")
    
    try:
        # Configuration
        images_folder = "images"
        output_file = "output.csv"
        
        # Check if images folder exists
        if not Path(images_folder).exists():
            logger.error(f"Images folder {{images_folder}} not found!")
            return
        
        # Phase 1: Load and preprocess images
        logger.info("Phase 1: Loading and preprocessing images...")
        {preprocessing.main_preprocessing_code if preprocessing else "# Preprocessing code will be added here"}
        
        # Phase 2: Model inference
        logger.info("Phase 2: Running model inference...")
        {processing.main_processing_code if processing else "# Processing code will be added here"}
        
        # Phase 3: Prime classification and CSV export
        logger.info("Phase 3: Prime classification and CSV generation...")
        
        # Apply prime logic to predictions
        results = []
        # This will be populated by the processing phase
        digit_predictions = {{}}  # filename -> predicted_digit
        
        for filename, predicted_digit in digit_predictions.items():
            prime_label = digit_to_prime_label(predicted_digit)
            results.append({{
                'file_name': filename,
                'prediction': prime_label
            }})
        
        # Create CSV
        df = pd.DataFrame(results)
        df.to_csv(output_file, index=False)
        
        logger.info(f"Pipeline completed! Results saved to {{output_file}}")
        logger.info(f"Processed {{len(results)}} images")
        
        # Print statistics
        prime_count = sum(1 for r in results if r['prediction'] == 'số nguyên tố')
        non_prime_count = len(results) - prime_count
        logger.info(f"Prime numbers: {{prime_count}}, Non-prime: {{non_prime_count}}")
        
    except Exception as e:
        logger.error(f"Error in pipeline: {{e}}")
        raise

if __name__ == "__main__":
    main()
'''
    
    with open(script_filename, 'w', encoding='utf-8') as f:
        f.write(final_script_content)
    
    print(f"📄 Final script created: {script_filename}")
    return str(script_filename)

def display_pipeline_summary(results: Dict[str, Any]):
    """Hiển thị tóm tắt pipeline execution"""
    print("\n" + "="*100)
    print("📊 MULTIAGENT PIPELINE EXECUTION SUMMARY")
    print("="*100)
    
    phases = [
        ("guideline", "🎯 Guideline Creation"),
        ("model_selection", "🤖 Model Selection"),
        ("preprocessing_code", "🛠️ Preprocessing Code"),
        ("processing_code", "⚙️ Processing Code"),
        ("postprocessing_code", "📊 Postprocessing Code")
    ]
    
    for phase_key, phase_name in phases:
        if phase_key in results and results[phase_key]:
            print(f"   ✅ {phase_name}")
        else:
            print(f"   ❌ {phase_name}")
    
    if 'model_selection' in results and results['model_selection']:
        print(f"\n🤖 Selected Models:")
        for model in results['model_selection'].selected_models:
            print(f"   • {model}")
    
    print("\n🎯 Expected Output: output.csv with columns [file_name, prediction]")
    print("📊 Prediction Values: 'số nguyên tố' hoặc 'không nguyên tố'")