#!/usr/bin/env python3
"""
DIGIT TO PRIME CLASSIFIER
Generated by MultiAgent System at: 2025-06-20 09:55:19

Task: Classify handwritten digits as prime or non-prime numbers
Input: Images folder with 28x28 grayscale digit images
Output: CSV file with file_name and prediction columns
"""

from transformers import AutoTokenizer
import pandas as pd
import numpy as np
import os
from pathlib import Path
import gdown
import json

import pandas as pd
import numpy as np
from pathlib import Path
import logging

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Prime number checker
def is_prime(digit):
    """Check if digit 0-9 is prime number"""
    prime_digits = {2, 3, 5, 7}
    return digit in prime_digits

def digit_to_prime_label(digit):
    """Convert digit to prime/non-prime label"""
    if is_prime(digit):
        return "số nguyên tố"
    else:
        return "không nguyên tố"

def clean_text(text):
    return text.strip().lower()

def tokenize_texts(texts, tokenizer, max_length=512):
    return tokenizer(texts, truncation=True, padding=True, max_length=max_length, return_tensors='pt')

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import logging

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def load_model(model_name):
    try:
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = AutoModelForSequenceClassification.from_pretrained(model_name)
        
        # Check for CUDA availability and move model to GPU if available
        if torch.cuda.is_available():
            device = torch.device('cuda')
            model.to(device)
            logging.info(f'Model loaded to CUDA device.')
        elif torch.backends.mps.is_available():
            device = torch.device('mps')
            model.to(device)
            logging.info(f'Model loaded to MPS device.')
        else:
            device = torch.device('cpu')
            logging.info('CUDA not available, using CPU.')
        
        model.eval()
        return model, tokenizer, device
    except Exception as e:
        logging.error(f'Error loading model {model_name}: {e}')
        raise

model_name = "thanhtlx/text_classification_1"
model, tokenizer, device = load_model(model_name)

def predict(text, model, tokenizer, device):
    try:
        # Tokenize the input text
        inputs = tokenizer(text, padding=True, truncation=True, return_tensors="pt").to(device)

        # Disable gradient calculation for inference
        with torch.no_grad():
            # Get model predictions
            outputs = model(**inputs)

        # Get predicted class probabilities
        probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)

        # Get the predicted class
        predicted_class = torch.argmax(probabilities, dim=-1).item()

        # Get the confidence score
        confidence_score = probabilities[0, predicted_class].item()

        return predicted_class, confidence_score

    except Exception as e:
        logging.error(f'Inference error: {e}')
        return None, None

```python
import pandas as pd
import logging
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class_labels = {0: 'Marketplace', 1: 'Recreation', 2: 'Technology', 3: 'Politics', 4: 'Religion'}

def load_model(model_name):
    try:
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = AutoModelForSequenceClassification.from_pretrained(model_name)
        
        # Check for CUDA availability and move model to GPU if available
        if torch.cuda.is_available():
            device = torch.device('cuda')
            model.to(device)
            logging.info(f'Model loaded to CUDA device.')
        elif torch.backends.mps.is_available():
            device = torch.device('mps')
            model.to(device)
            logging.info(f'Model loaded to MPS device.')
        else:
            device = torch.device('cpu')
            logging.info('CUDA not available, using CPU.')
        
        model.eval()
        return model, tokenizer, device
    except Exception as e:
        logging.error(f'Error loading model {model_name}: {e}')
        raise

def predict(text, model, tokenizer, device):
    try:
        # Tokenize the input text
        inputs = tokenizer(text, padding=True, truncation=True, return_tensors="pt").to(device)

        # Disable gradient calculation for inference
        with torch.no_grad():
            # Get model predictions
            outputs = model(**inputs)

        # Get predicted class probabilities
        probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)

        # Get the predicted class
        predicted_class = torch.argmax(probabilities, dim=-1).item()

        # Get the confidence score
        confidence_score = probabilities[0, predicted_class].item()

        return predicted_class, confidence_score

    except Exception as e:
        logging.error(f'Inference error: {e}')
        return None, None


def format_output(predicted_class_index, confidence_score):
    label = class_labels.get(predicted_class_index)
    if label is None:
        logging.error(f'Invalid class index: {predicted_class_index}')
        return None, None
    return label, confidence_score
```

def main():
    """Main execution function"""
    logger.info("Starting Digit to Prime Classification Pipeline...")
    
    try:
        # Configuration
        images_folder = "images"
        output_file = "output.csv"
        
        # Check if images folder exists
        if not Path(images_folder).exists():
            logger.error(f"Images folder {images_folder} not found!")
            return
        
        # Phase 1: Load and preprocess images
        logger.info("Phase 1: Loading and preprocessing images...")
        # Download and preprocess text data
download_from_drive(drive_url, 'data/')
texts = pd.read_csv('data/texts.csv')
tokenizer = AutoTokenizer.from_pretrained(model_name)
encoded = tokenize_texts(texts['text'].tolist(), tokenizer)
        
        # Phase 2: Model inference
        logger.info("Phase 2: Running model inference...")
        import pandas as pd

def process_data(csv_file, model, tokenizer, device):
    try:
        # Load the CSV file using pandas
        df = pd.read_csv(csv_file)

        # Check if the DataFrame is empty
        if df.empty:
            logging.warning("The DataFrame is empty.")
            return

        # Check if 'text' column exists
        if 'text' not in df.columns:
            logging.error("'text' column not found in the CSV file.")
            return

        # Create lists to store predictions and confidence scores
        predictions = []
        confidence_scores = []

        # Iterate over each row in the DataFrame
        for index, row in df.iterrows():
            text = row['text']

            # Perform inference
            predicted_class, confidence_score = predict(text, model, tokenizer, device)

            # Append the results to the lists
            predictions.append(predicted_class)
            confidence_scores.append(confidence_score)

        # Add the predictions and confidence scores to the DataFrame
        df['predicted_class'] = predictions
        df['confidence_score'] = confidence_scores

        # Print the updated DataFrame
        print(df)

        # Save the updated DataFrame to a new CSV file
        df.to_csv('predictions.csv', index=False)

    except FileNotFoundError:
        logging.error(f"File not found: {csv_file}")
    except pd.errors.EmptyDataError:
        logging.error(f"The file {csv_file} is empty.")
    except pd.errors.ParserError:
        logging.error(f"Error parsing the file {csv_file}. Please ensure it is a valid CSV file.")
    except Exception as e:
        logging.error(f"An error occurred: {e}")

# Example usage
csv_file = 'data/texts.csv'  # Replace with the path to your CSV file
process_data(csv_file, model, tokenizer, device)
        
        # Phase 3: Prime classification and CSV export
        logger.info("Phase 3: Prime classification and CSV generation...")
        
        # Apply prime logic to predictions
        results = []
        # This will be populated by the processing phase
        digit_predictions = {}  # filename -> predicted_digit
        
        for filename, predicted_digit in digit_predictions.items():
            prime_label = digit_to_prime_label(predicted_digit)
            results.append({
                'file_name': filename,
                'prediction': prime_label
            })
        
        # Create CSV
        df = pd.DataFrame(results)
        df.to_csv(output_file, index=False)
        
        logger.info(f"Pipeline completed! Results saved to {output_file}")
        logger.info(f"Processed {len(results)} images")
        
        # Print statistics
        prime_count = sum(1 for r in results if r['prediction'] == 'số nguyên tố')
        non_prime_count = len(results) - prime_count
        logger.info(f"Prime numbers: {prime_count}, Non-prime: {non_prime_count}")
        
    except Exception as e:
        logger.error(f"Error in pipeline: {e}")
        raise

if __name__ == "__main__":
    main()
