#!/usr/bin/env python3
"""
DIGIT TO PRIME CLASSIFIER
Generated by MultiAgent System at: 2025-06-20 09:44:24

Task: Classify handwritten digits as prime or non-prime numbers
Input: Images folder with 28x28 grayscale digit images
Output: CSV file with file_name and prediction columns
"""

import os
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import load_model
import logging
import requests
import io
from PIL import Image

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

import pandas as pd
import numpy as np
from pathlib import Path
import logging

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Prime number checker
def is_prime(digit):
    """Check if digit 0-9 is prime number"""
    prime_digits = {2, 3, 5, 7}
    return digit in prime_digits

def digit_to_prime_label(digit):
    """Convert digit to prime/non-prime label"""
    if is_prime(digit):
        return "số nguyên tố"
    else:
        return "không nguyên tố"

def download_data_from_google_drive(drive_url, destination_path):
    """Downloads a zip file from Google Drive and extracts it."""
    try:
        file_id = drive_url.split('/folders/')[1]
        download_url = f'https://drive.google.com/uc?export=download&id={file_id}'
        
        session = requests.Session()
        response = session.get(download_url, stream=True)

        if response.status_code == 200:
            # Extract the zip file
            import zipfile
            with zipfile.ZipFile(io.BytesIO(response.content)) as zip_ref:
                zip_ref.extractall(destination_path)
            logging.info(f'Successfully downloaded and extracted data to {destination_path}')
        else:
            logging.error(f'Failed to download data. Status code: {response.status_code}')
    except Exception as e:
        logging.error(f'Error downloading and extracting data: {e}')

def load_and_preprocess_image(image_path):
    """Loads, preprocesses, and reshapes an image."""
    try:
        img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            raise ValueError(f"Could not read image at {image_path}")
        img = img.astype('float32') / 255.0
        img = np.expand_dims(img, axis=-1)
        return img
    except Exception as e:
        logging.error(f"Error loading and preprocessing image {image_path}: {e}")
        return None

def predict_digit(model, image):
    """Predicts the digit in the image using the provided model."""
    try:
        img_batch = np.expand_dims(image, axis=0)
        prediction = model.predict(img_batch)
        digit = np.argmax(prediction)
        return digit
    except Exception as e:
        logging.error(f"Error predicting digit: {e}")
        return None

def classify_prime(digit):
    """Classifies a digit as prime or non-prime."""
    prime_numbers = {2, 3, 5, 7}
    if digit in prime_numbers:
        return 'số nguyên tố'
    else:
        return 'không nguyên tố'

import os
import cv2
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import load_model
import logging
import requests
import io
from PIL import Image

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Function to attempt loading the model from different sources
def load_model_adaptive(model_path):
    """Attempts to load the model from a local file, then from TensorFlow Hub, and finally raises an exception if all fail."""
    try:
        model = load_model(model_path)
        logging.info(f"Model loaded successfully from {model_path}")
        return model
    except Exception as e_local:
        logging.warning(f"Failed to load model from local path {model_path}: {e_local}")
        try:
            model = tf.keras.models.load_model('thanhtlx/image_classification_01')
            logging.info("Model loaded successfully from TensorFlow Hub.")
            return model
        except Exception as e_hub:
            logging.error(f"Failed to load model from TensorFlow Hub: {e_hub}")
            raise Exception("Failed to load model from any source.")

# Determine device for optimized execution
def get_device():
    """Determines the available device (GPU or CPU) and returns the device name."""
    try:
        # Check for GPU availability
        gpus = tf.config.list_physical_devices('GPU')
        if gpus:
            device = '/GPU:0'
            logging.info("GPU device found.")
        else:
            device = '/CPU:0'
            logging.info("No GPU found, using CPU.")
    except Exception as e:
        device = '/CPU:0'
        logging.error(f"Error detecting GPU, defaulting to CPU: {e}")
    return device

def preprocess_image(image_path, target_size=(28, 28)):
    """Loads, preprocesses, and reshapes an image to the target size. Handles grayscale conversion and normalization."""
    try:
        img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            raise ValueError(f"Could not read image at {image_path}")

        # Resize image if necessary
        if img.shape[:2] != target_size:
            img = cv2.resize(img, target_size, interpolation=cv2.INTER_AREA)

        img = img.astype('float32') / 255.0
        img = np.expand_dims(img, axis=-1)
        return img
    except Exception as e:
        logging.error(f"Error loading and preprocessing image {image_path}: {e}")
        return None

def predict_digit(model, image, device='/CPU:0'):
    """Predicts the digit in the image using the provided model. Runs inference on the specified device."""
    try:
        with tf.device(device):
            img_batch = np.expand_dims(image, axis=0)
            prediction = model.predict(img_batch)
            digit = np.argmax(prediction)
            confidence = np.max(prediction)
            return digit, confidence
    except Exception as e:
        logging.error(f"Error predicting digit: {e}")
        return None, None

def classify_prime(digit):
    """Classifies a digit as prime or non-prime."""
    prime_numbers = {2, 3, 5, 7}
    if digit in prime_numbers:
        return 'số nguyên tố'
    else:
        return 'không nguyên tố'

The output is formatted as a CSV file with two columns: 'file_name' and 'prediction'. The 'file_name' column contains the name of the image file, and the 'prediction' column contains the classification result ('số nguyên tố' or 'không nguyên tố'). A 'confidence' column is also included to show the confidence score of the prediction.

def main():
    """Main execution function"""
    logger.info("Starting Digit to Prime Classification Pipeline...")
    
    try:
        # Configuration
        images_folder = "images"
        output_file = "output.csv"
        
        # Check if images folder exists
        if not Path(images_folder).exists():
            logger.error(f"Images folder {images_folder} not found!")
            return
        
        # Phase 1: Load and preprocess images
        logger.info("Phase 1: Loading and preprocessing images...")
        # Define paths and variables
drive_url = 'https://drive.google.com/drive/folders/1cijuTQmFaSew7IueB9eotOPYg1M90ppP'
image_folder = 'test_images'
output_csv = 'output.csv'
model_path = 'image_classification_model.h5' # Path to the saved model

# Create the image folder if it doesn't exist
os.makedirs(image_folder, exist_ok=True)

# Download data from Google Drive
download_data_from_google_drive(drive_url, image_folder)

# Load the pre-trained model
try:
    model = load_model(model_path)
    logging.info("Model loaded successfully.")
except Exception as e:
    logging.error(f"Error loading the model: {e}")
    # Attempt to load the model from the local directory if the above fails
    try:
        model = tf.keras.models.load_model('thanhtlx/image_classification_01')
        logging.info("Model loaded successfully from local directory.")
    except Exception as e2:
        logging.error(f"Error loading the model from local directory: {e2}")
        model = None # Ensure model is None if loading fails

# Process images and create predictions
results = []
if model is not None:
    for filename in os.listdir(image_folder):
        if filename.endswith('.png'):
            image_path = os.path.join(image_folder, filename)
            image = load_and_preprocess_image(image_path)
            if image is not None:
                digit = predict_digit(model, image)
                if digit is not None:
                    classification = classify_prime(digit)
                    results.append({'file_name': filename, 'prediction': classification})
                else:
                    logging.warning(f"Could not predict digit for {filename}")
            else:
                logging.warning(f"Could not load/preprocess {filename}")
else:
    logging.error("Model not loaded. Skipping image processing.")

# Convert results to DataFrame and save to CSV
df = pd.DataFrame(results)
df.to_csv(output_csv, index=False)

logging.info(f"Results saved to {output_csv}")
        
        # Phase 2: Model inference
        logger.info("Phase 2: Running model inference...")
        # Define paths and variables
drive_url = 'https://drive.google.com/drive/folders/1cijuTQmFaSew7IueB9eotOPYg1M90ppP'
image_folder = 'test_images'
output_csv = 'output.csv'
model_path = 'image_classification_model.h5' # Path to the saved model

# Create the image folder if it doesn't exist
os.makedirs(image_folder, exist_ok=True)

# Function to download data from Google Drive
def download_data_from_google_drive(drive_url, destination_path):
    """Downloads a zip file from Google Drive and extracts it."""
    try:
        file_id = drive_url.split('/folders/')[1]
        download_url = f'https://drive.google.com/uc?export=download&id={file_id}'
        
        session = requests.Session()
        response = session.get(download_url, stream=True)

        if response.status_code == 200:
            # Extract the zip file
            import zipfile
            with zipfile.ZipFile(io.BytesIO(response.content)) as zip_ref:
                zip_ref.extractall(destination_path)
            logging.info(f'Successfully downloaded and extracted data to {destination_path}')
        else:
            logging.error(f'Failed to download data. Status code: {response.status_code}')
    except Exception as e:
        logging.error(f'Error downloading and extracting data: {e}')

# Download data from Google Drive
download_data_from_google_drive(drive_url, image_folder)

# Load the model
try:
    model = load_model_adaptive(model_path)
except Exception as e:
    logging.error(f"Failed to load model: {e}")
    model = None

# Determine the device
device = get_device()

# Process images and create predictions
results = []
if model is not None:
    for filename in os.listdir(image_folder):
        if filename.endswith('.png'):
            image_path = os.path.join(image_folder, filename)
            image = preprocess_image(image_path)
            if image is not None:
                digit, confidence = predict_digit(model, image, device)
                if digit is not None:
                    classification = classify_prime(digit)
                    results.append({'file_name': filename, 'prediction': classification, 'confidence': confidence})
                else:
                    logging.warning(f"Could not predict digit for {filename}")
            else:
                logging.warning(f"Could not load/preprocess {filename}")
else:
    logging.error("Model not loaded. Skipping image processing.")

# Convert results to DataFrame and save to CSV
df = pd.DataFrame(results)
df.to_csv(output_csv, index=False)

logging.info(f"Results saved to {output_csv}")
        
        # Phase 3: Prime classification and CSV export
        logger.info("Phase 3: Prime classification and CSV generation...")
        
        # Apply prime logic to predictions
        results = []
        # This will be populated by the processing phase
        digit_predictions = {}  # filename -> predicted_digit
        
        for filename, predicted_digit in digit_predictions.items():
            prime_label = digit_to_prime_label(predicted_digit)
            results.append({
                'file_name': filename,
                'prediction': prime_label
            })
        
        # Create CSV
        df = pd.DataFrame(results)
        df.to_csv(output_file, index=False)
        
        logger.info(f"Pipeline completed! Results saved to {output_file}")
        logger.info(f"Processed {len(results)} images")
        
        # Print statistics
        prime_count = sum(1 for r in results if r['prediction'] == 'số nguyên tố')
        non_prime_count = len(results) - prime_count
        logger.info(f"Prime numbers: {prime_count}, Non-prime: {non_prime_count}")
        
    except Exception as e:
        logger.error(f"Error in pipeline: {e}")
        raise

if __name__ == "__main__":
    main()
