#!/usr/bin/env python3
"""
DIGIT TO PRIME CLASSIFIER
Generated by MultiAgent System at: 2025-06-20 06:00:32

Task: Classify handwritten digits as prime or non-prime numbers
Input: Images folder with 28x28 grayscale digit images
Output: CSV file with file_name and prediction columns
"""

import os
import re
import string
import logging
from pathlib import Path
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer
import torch
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from io import BytesIO
import zipfile


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

import pandas as pd
import numpy as np
from pathlib import Path
import logging

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Prime number checker
def is_prime(digit):
    """Check if digit 0-9 is prime number"""
    prime_digits = {2, 3, 5, 7}
    return digit in prime_digits

def digit_to_prime_label(digit):
    """Convert digit to prime/non-prime label"""
    if is_prime(digit):
        return "số nguyên tố"
    else:
        return "không nguyên tố"

def download_and_unzip_from_drive(file_id, destination_path):
    """Downloads a zip file from Google Drive and extracts it."""
    try:
        # Authenticate with Google Drive API
        creds = None
        # Check if running in a Google Colab environment
        if 'COLAB_TPU_ADDR' in os.environ:
            from google.colab import auth
            auth.authenticate_user()
            creds, _ = google.auth.default()
        else:
            # Use a service account if not in Colab
            key_path = 'path/to/your/service_account_key.json'  # Replace with your key path
            creds = service_account.Credentials.from_service_account_file(key_path)

        service = build('drive', 'v3', credentials=creds)

        # Get the file
        file = service.files().get(fileId=file_id, supportsAllDrives=True, fields='name').execute()
        file_name = file.get('name')

        # Download the file
        request = service.files().get_media(fileId=file_id, supportsAllDrives=True)
        response = request.execute()

        # Save the file to a BytesIO object
        zip_file = BytesIO(response)

        # Extract the zip file
        with zipfile.ZipFile(zip_file, 'r') as zip_ref:
            zip_ref.extractall(destination_path)

        logging.info(f'Successfully downloaded and extracted {file_name} to {destination_path}')
    except HttpError as error:
        logging.error(f'An error occurred: {error}')
    except Exception as e:
        logging.error(f'An unexpected error occurred: {e}')


def clean_text(text):
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\S+', '', text)
    text = re.sub(r'#\S+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = text.lower()
    text = re.sub(r'\w*\d+\w*', '', text)
    text = re.sub('\s+', ' ', text).strip()
    return text


def encode_labels(labels):
    label_encoder = LabelEncoder()
    encoded_labels = label_encoder.fit_transform(labels)
    return encoded_labels, label_encoder


def tokenize_data(texts, tokenizer_name, max_length=512):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    tokenized = tokenizer(texts, padding='max_length', truncation=True, max_length=max_length, return_tensors='pt')
    return tokenized


import os
import logging
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class ModelLoader:
    def __init__(self, model_name):
        self.model_name = model_name
        self.model = None
        self.tokenizer = None
        self.device = self._get_device()

    def _get_device(self):
        if torch.cuda.is_available():
            device = torch.device('cuda')
            logging.info("CUDA device detected.")
        elif torch.backends.mps.is_available():
            device = torch.device('mps')
            logging.info("MPS device detected.")
        else:
            device = torch.device('cpu')
            logging.info("No CUDA or MPS, using CPU.")
        return device

    def load_model(self):
        try:
            self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
            self.model = AutoModelForSequenceClassification.from_pretrained(self.model_name).to(self.device)
            self.model.eval()
            logging.info(f"Model '{self.model_name}' loaded successfully on {self.device}.")
        except Exception as e:
            logging.error(f"Error loading model '{self.model_name}': {e}")
            raise

    def get_model(self):
        if self.model is None:
            self.load_model()
        return self.model, self.tokenizer, self.device

import torch
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class InferencePipeline:
    def __init__(self, model, tokenizer, device, label_encoder):
        self.model = model
        self.tokenizer = tokenizer
        self.device = device
        self.label_encoder = label_encoder

    def predict(self, text):
        try:
            # Tokenize the input text
            inputs = self.tokenizer(text, padding=True, truncation=True, return_tensors='pt').to(self.device)

            # Disable gradient calculation for inference
            with torch.no_grad():
                # Perform inference
                outputs = self.model(**inputs)

            # Get predicted probabilities
            probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)

            # Get the predicted class
            predicted_class_id = torch.argmax(probabilities, dim=-1).item()

            # Decode the predicted label
            predicted_label = self.label_encoder.inverse_transform([predicted_class_id])[0]

            # Get the confidence score
            confidence_score = probabilities[0, predicted_class_id].item()

            logging.info(f"Input text: {text}\nPredicted label: {predicted_label}\nConfidence score: {confidence_score}")

            return predicted_label, confidence_score

        except Exception as e:
            logging.error(f"Inference error: {e}")
            return None, None

```python
import pandas as pd
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class OutputFormatter:
    def __init__(self, label_encoder):
        self.label_encoder = label_encoder

    def format_classification_output(self, predictions, confidence_scores):
        """Formats classification output with readable labels and confidence scores."""
        try:
            # Convert numerical predictions to readable labels
            labels = self.label_encoder.inverse_transform(predictions)
            
            # Create a list of dictionaries, each containing the file name, prediction, and confidence
            formatted_output = [{'prediction': label, 'confidence': confidence} for label, confidence in zip(labels, confidence_scores)]
            
            logging.info("Classification output formatted successfully.")
            return formatted_output
        except Exception as e:
            logging.error(f"Error formatting classification output: {e}")
            return None

    def validate_output(self, output):
        """Validates the formatted output."""
        if not isinstance(output, list):
            logging.error("Output is not a list.")
            return False
        for item in output:
            if not isinstance(item, dict):
                logging.error("Item in output is not a dictionary.")
                return False
            if 'prediction' not in item or 'confidence' not in item:
                logging.error("Item in output does not contain 'prediction' or 'confidence' keys.")
                return False
        logging.info("Output validation successful.")
        return True
```

def main():
    """Main execution function"""
    logger.info("Starting Digit to Prime Classification Pipeline...")
    
    try:
        # Configuration
        images_folder = "images"
        output_file = "output.csv"
        
        # Check if images folder exists
        if not Path(images_folder).exists():
            logger.error(f"Images folder {images_folder} not found!")
            return
        
        # Phase 1: Load and preprocess images
        logger.info("Phase 1: Loading and preprocessing images...")
        # Define paths and constants
data_dir = Path('./data')
data_dir.mkdir(exist_ok=True)
train_file = data_dir / 'train.csv'
test_file = data_dir / 'test.csv'
sample_submission_file = data_dir / 'sample_submission.csv'
MODEL_NAME = 'thanhtlx/text_classification_1'
DRIVE_FILE_ID = '1yrSszfKlU8Tk9tySPxlA_tbPya9Wi7uQ' # Google Drive folder ID

# Download and extract data from Google Drive
download_and_unzip_from_drive(DRIVE_FILE_ID, data_dir)

# Load data
try:
    train_df = pd.read_csv(train_file)
    test_df = pd.read_csv(test_file)
    sample_submission_df = pd.read_csv(sample_submission_file)
    logging.info("Data loaded successfully.")
except FileNotFoundError as e:
    logging.error(f"File not found: {e}")
    raise e
except pd.errors.EmptyDataError as e:
    logging.error(f"The CSV file is empty: {e}")
    raise e
except pd.errors.ParserError as e:
    logging.error(f"Error parsing the CSV file: {e}")
    raise e
except Exception as e:
    logging.error(f"An unexpected error occurred while loading data: {e}")
    raise e

# Handle missing values
train_df.dropna(subset=['text', 'label'], inplace=True)
test_df.fillna('', inplace=True) # Fill missing text with empty string

# Clean text data
train_df['text'] = train_df['text'].apply(clean_text)
test_df['text'] = test_df['text'].apply(clean_text)

# Encode labels
encoded_labels, label_encoder = encode_labels(train_df['label'])
train_df['encoded_label'] = encoded_labels

# Split data into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(train_df['text'], train_df['encoded_label'], test_size=0.2, random_state=42)

# Tokenize data
train_tokenized = tokenize_data(train_texts.tolist(), MODEL_NAME)
val_tokenized = tokenize_data(val_texts.tolist(), MODEL_NAME)
test_tokenized = tokenize_data(test_df['text'].tolist(), MODEL_NAME)

# Prepare data for model input
train_input_ids = train_tokenized['input_ids']
train_attention_mask = train_tokenized['attention_mask']
val_input_ids = val_tokenized['input_ids']
val_attention_mask = val_tokenized['attention_mask']
test_input_ids = test_tokenized['input_ids']
test_attention_mask = test_tokenized['attention_mask']

train_labels = torch.tensor(train_labels.tolist())
val_labels = torch.tensor(val_labels.tolist())

logging.info("Data preprocessing complete.")
        
        # Phase 2: Model inference
        logger.info("Phase 2: Running model inference...")
        import logging
import pandas as pd
from pathlib import Path
from model_loader import ModelLoader
from inference_pipeline import InferencePipeline
import torch

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def main(model_name, test_file_path, output_file_path, label_encoder):
    try:
        # Load the test data
        test_df = pd.read_csv(test_file_path)

        # Initialize ModelLoader
        model_loader = ModelLoader(model_name)

        # Load the model, tokenizer, and device
        model, tokenizer, device = model_loader.get_model()

        # Initialize InferencePipeline
        inference_pipeline = InferencePipeline(model, tokenizer, device, label_encoder)

        # Create lists to store predictions and confidence scores
        predicted_labels = []
        confidence_scores = []

        # Iterate over the test data and make predictions
        for text in test_df['text']:
            predicted_label, confidence_score = inference_pipeline.predict(text)
            predicted_labels.append(predicted_label)
            confidence_scores.append(confidence_score)

        # Add the predictions and confidence scores to the test DataFrame
        test_df['label'] = predicted_labels
        test_df['confidence'] = confidence_scores

        # Save the updated DataFrame to a CSV file
        test_df.to_csv(output_file_path, index=False)

        logging.info(f"Predictions saved to {output_file_path}")

    except FileNotFoundError:
        logging.error(f"Test file not found: {test_file_path}")
    except Exception as e:
        logging.error(f"An error occurred during the main processing: {e}")

if __name__ == '__main__':
    # Define paths and constants
    MODEL_NAME = 'thanhtlx/text_classification_1'
    TEST_FILE_PATH = './data/test.csv'
    OUTPUT_FILE_PATH = './data/submission.csv'

    # Load label encoder (assuming it's saved as a pickle file)
    import joblib
    label_encoder = joblib.load('./data/label_encoder.pkl')

    # Run the main function
    main(MODEL_NAME, TEST_FILE_PATH, OUTPUT_FILE_PATH, label_encoder)
        
        # Phase 3: Prime classification and CSV export
        logger.info("Phase 3: Prime classification and CSV generation...")
        
        # Apply prime logic to predictions
        results = []
        # This will be populated by the processing phase
        digit_predictions = {}  # filename -> predicted_digit
        
        for filename, predicted_digit in digit_predictions.items():
            prime_label = digit_to_prime_label(predicted_digit)
            results.append({
                'file_name': filename,
                'prediction': prime_label
            })
        
        # Create CSV
        df = pd.DataFrame(results)
        df.to_csv(output_file, index=False)
        
        logger.info(f"Pipeline completed! Results saved to {output_file}")
        logger.info(f"Processed {len(results)} images")
        
        # Print statistics
        prime_count = sum(1 for r in results if r['prediction'] == 'số nguyên tố')
        non_prime_count = len(results) - prime_count
        logger.info(f"Prime numbers: {prime_count}, Non-prime: {non_prime_count}")
        
    except Exception as e:
        logger.error(f"Error in pipeline: {e}")
        raise

if __name__ == "__main__":
    main()
