#!/usr/bin/env python3
"""
DIGIT TO PRIME CLASSIFIER
Generated by MultiAgent System at: 2025-06-20 10:15:43

Task: Classify handwritten digits as prime or non-prime numbers
Input: Images folder with 28x28 grayscale digit images
Output: CSV file with file_name and prediction columns
"""

from transformers import AutoTokenizer
import pandas as pd
import numpy as np
import os
from pathlib import Path
import gdown
import json

import pandas as pd
import numpy as np
from pathlib import Path
import logging

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Prime number checker
def is_prime(digit):
    """Check if digit 0-9 is prime number"""
    prime_digits = {2, 3, 5, 7}
    return digit in prime_digits

def digit_to_prime_label(digit):
    """Convert digit to prime/non-prime label"""
    if is_prime(digit):
        return "số nguyên tố"
    else:
        return "không nguyên tố"

def clean_text(text):
    return text.strip().lower()

def tokenize_texts(texts, tokenizer, max_length=512):
    return tokenizer(texts, truncation=True, padding=True, max_length=max_length, return_tensors='pt')

import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler
import joblib
import os

# Configuration
MODEL_URL = "https://huggingface.co/zhaospei/Model_2/resolve/main/model.pth"
SCALER_URL = "https://huggingface.co/zhaospei/Model_2/resolve/main/scaler.pkl"
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Define the Wide and Deep model architecture
class WideDeepModel(torch.nn.Module):
    def __init__(self, num_features):
        super(WideDeepModel, self).__init__()
        self.linear = torch.nn.Linear(num_features, 1)
        self.deep = torch.nn.Sequential(
            torch.nn.Linear(num_features, 64),
            torch.nn.ReLU(),
            torch.nn.Linear(64, 32),
            torch.nn.ReLU(),
            torch.nn.Linear(32, 1)
        )

    def forward(self, x):
        wide_out = self.linear(x)
        deep_out = self.deep(x)
        combined_out = wide_out + deep_out  # Combine wide and deep outputs
        return combined_out


def download_file(url, filename):
    if not os.path.exists(filename):
        try:
            torch.hub.download_url_to_file(url, filename)
            print(f"Downloaded {filename} from {url}")
        except Exception as e:
            print(f"Error downloading {filename}: {e}")
            return False
    return True


def load_model_and_scaler():
    # Download model and scaler
    model_filename = "model.pth"
    scaler_filename = "scaler.pkl"

    model_downloaded = download_file(MODEL_URL, model_filename)
    scaler_downloaded = download_file(SCALER_URL, scaler_filename)

    if not model_downloaded or not scaler_downloaded:
        raise FileNotFoundError("Failed to download model or scaler.")

    # Load scaler
    try:
        scaler = joblib.load(scaler_filename)
        print("Scaler loaded successfully.")
    except Exception as e:
        raise Exception(f"Error loading scaler: {e}")

    # Load model
    try:
        model = WideDeepModel(num_features=8)  # Assuming 8 features
        model.load_state_dict(torch.load(model_filename, map_location=DEVICE))
        model.to(DEVICE)
        model.eval()
        print("Model loaded successfully.")
    except Exception as e:
        raise Exception(f"Error loading model: {e}")

    return model, scaler

def preprocess_data(df, scaler):
    numerical_features = ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
    df_numerical = df[numerical_features].copy()

    # Handle missing values with median imputation
    for col in numerical_features:
        median_val = df_numerical[col].median()
        df_numerical[col] = df_numerical[col].fillna(median_val)

    scaled_features = scaler.transform(df_numerical)
    return scaled_features

def predict_labels(model, scaled_features):
    model.eval()
    with torch.no_grad():
        inputs = torch.tensor(scaled_features, dtype=torch.float32).to(DEVICE)
        predictions = model(inputs)
        predictions = predictions.cpu().numpy().flatten()
    return predictions

def map_predictions_to_labels(predictions):
    labels = []
    for prediction in predictions:
        if prediction < 1:
            labels.append('low')
        elif 1 <= prediction < 2.5:
            labels.append('medium')
        else:
            labels.append('high')
    return labels

def map_predictions_to_labels(predictions):
    """Maps continuous predictions to categorical labels based on defined thresholds."""
    labels = []
    for prediction in predictions:
        if prediction < 1:
            labels.append('low')
        elif 1 <= prediction < 2.5:
            labels.append('medium')
        else:
            labels.append('high')
    return labels

def main():
    """Main execution function"""
    logger.info("Starting Digit to Prime Classification Pipeline...")
    
    try:
        # Configuration
        images_folder = "images"
        output_file = "output.csv"
        
        # Check if images folder exists
        if not Path(images_folder).exists():
            logger.error(f"Images folder {images_folder} not found!")
            return
        
        # Phase 1: Load and preprocess images
        logger.info("Phase 1: Loading and preprocessing images...")
        # Download and preprocess text data
download_from_drive(drive_url, 'data/')
texts = pd.read_csv('data/texts.csv')
tokenizer = AutoTokenizer.from_pretrained(model_name)
encoded = tokenize_texts(texts['text'].tolist(), tokenizer)
        
        # Phase 2: Model inference
        logger.info("Phase 2: Running model inference...")
        def main():
    try:
        model, scaler = load_model_and_scaler()
    except Exception as e:
        print(f"Failed to load model or scaler: {e}")
        return

    try:
        test_df = pd.read_csv('test.csv')
    except FileNotFoundError:
        print("Error: test.csv not found.")
        return
    except Exception as e:
        print(f"Error reading test.csv: {e}")
        return

    try:
        ids = test_df['ID']
        scaled_features = preprocess_data(test_df, scaler)
        predictions = predict_labels(model, scaled_features)
        labels = map_predictions_to_labels(predictions)

        output_df = pd.DataFrame({'ID': ids, 'MedHouseVal': labels})
        output_df.to_csv('output.csv', index=False)
        print("output.csv created successfully.")

    except Exception as e:
        print(f"Error during processing: {e}")

if __name__ == "__main__":
    main()
        
        # Phase 3: Prime classification and CSV export
        logger.info("Phase 3: Prime classification and CSV generation...")
        
        # Apply prime logic to predictions
        results = []
        # This will be populated by the processing phase
        digit_predictions = {}  # filename -> predicted_digit
        
        for filename, predicted_digit in digit_predictions.items():
            prime_label = digit_to_prime_label(predicted_digit)
            results.append({
                'file_name': filename,
                'prediction': prime_label
            })
        
        # Create CSV
        df = pd.DataFrame(results)
        df.to_csv(output_file, index=False)
        
        logger.info(f"Pipeline completed! Results saved to {output_file}")
        logger.info(f"Processed {len(results)} images")
        
        # Print statistics
        prime_count = sum(1 for r in results if r['prediction'] == 'số nguyên tố')
        non_prime_count = len(results) - prime_count
        logger.info(f"Prime numbers: {prime_count}, Non-prime: {non_prime_count}")
        
    except Exception as e:
        logger.error(f"Error in pipeline: {e}")
        raise

if __name__ == "__main__":
    main()
